### ISSUE TITLE
How do I open?

### ISSUE THREAD

**Issue by apanagar** [philzet/WWDC17#1]
Hi - This is probably a stupid question, but how do I open a Playground? I have a decade of experience with Xcode and iOS, but have never used the Playground feature

I'm trying to figure out how to use an SKScene as a SceneKit material, and it seems like you've done some of that.

Thanks

**Comment by philzet** [comment]
If you have the playground in Finder, choose "Show package contents," and then you'll be able to locate the Swift source. The Swift version might be outdated at this point, but you should be able to copy and paste the code into an Xcode project.

**Comment by apanagar** [comment]
Thanks!
